# numpy array operations

In [5]:
import numpy as np

In [6]:
arr=np.array([1 ,2 ,3 ,4 , 5, 6, 7, 8 , 9 ,10])
print("basic slicing" ,arr[2:7])
print("with steps" ,arr[1:8:2])
print("negative indexing" , arr[-3])

basic slicing [3 4 5 6 7]
with steps [2 4 6 8]
negative indexing 8


In [7]:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print("specific element" , arr_2d[1, 2])
print("specific row" , arr_2d[1])
print("specific column" , arr_2d[:, 1])

specific element 6
specific row [4 5 6]
specific column [2 5 8]


# sorting

In [8]:
unsorted_arr = np.array([3, 1, 2, 5, 4 , 3 , 2, 1 , 0 , 9 , 8, 7, 6])
print("sorted array:\n" , np.sort(unsorted_arr))

unsorted_2d= np.array([[3, 1, 2],
                       [5, 4, 3],
                       [2, 1, 0],
                       [9, 8, 7],
                       [6, 5, 4]])
print("sorted 2d array coloumnwise;\n" , np.sort(unsorted_2d, axis=0))
print("sorted 2d array rowwise:\n" , np.sort(unsorted_2d, axis=1))
print("sorted 2d array:\n" , np.sort(unsorted_2d, axis=None))

sorted array:
 [0 1 1 2 2 3 3 4 5 6 7 8 9]
sorted 2d array coloumnwise;
 [[2 1 0]
 [3 1 2]
 [5 4 3]
 [6 5 4]
 [9 8 7]]
sorted 2d array rowwise:
 [[1 2 3]
 [3 4 5]
 [0 1 2]
 [7 8 9]
 [4 5 6]]
sorted 2d array:
 [0 1 1 2 2 3 3 4 4 5 5 6 7 8 9]


# filter


In [9]:
num_arr = np.array([1, 2, 3, 4, 5 , 6, 7, 8, 9, 10])
even_arr = num_arr[num_arr % 2 == 0]
print("even numbers from array:\n" , even_arr)

even numbers from array:
 [ 2  4  6  8 10]


# filter by mask

In [10]:
mask=num_arr > 5
print("mask array:\n" , mask)
print("masked array:\n" , num_arr[mask])

mask array:
 [False False False False False  True  True  True  True  True]
masked array:
 [ 6  7  8  9 10]


# fancy indexing vs np.where()

In [11]:
indices=num_arr > 5
print("indices of masked array:\n" , num_arr[indices])
print("indices of masked array:\n" , np.where(indices))

print("indices of masked array:\n" , np.where(indices))
where_indices = np.where(num_arr > 5)
print("masked array:\n" , num_arr[where_indices])

indices of masked array:
 [ 6  7  8  9 10]
indices of masked array:
 (array([5, 6, 7, 8, 9]),)
indices of masked array:
 (array([5, 6, 7, 8, 9]),)
masked array:
 [ 6  7  8  9 10]


In [12]:
conditional_arr=np.where(num_arr > 5, "true", "false")
print("conditional array:\n" , conditional_arr)

conditional array:
 ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


# add and delete elements

In [13]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
combined_arr = np.concatenate((arr1, arr2))
print("concatenated array:\n" , combined_arr)

concatenated array:
 [ 1  2  3  4  5  6  7  8  9 10]


# array comparitibility

In [14]:
a=np.array([1 , 2, 3])
b=np.array([4 , 5, 6 , 9])
c=np.array([7 , 8, 9])
print("array compatibility a , b: ", a.shape==b.shape)
print("array compatibility a , c:", a.shape==c.shape)
print("array compatibility b , c:" ,b.shape==c.shape)

array compatibility a , b:  False
array compatibility a , c: True
array compatibility b , c: False


# adding new row or column

In [16]:
original=np.array([[1 , 2], [3 , 4]])
new_row=np.array([[5 , 6]])
combined_row=np.vstack((original, new_row))
print("original:\n" , original)
print()
print("combined row:\n" , combined_row)

new_col=np.array([[7], [8]])
combined_col=np.hstack((original, new_col))
print("combined column:\n" , combined_col)


original:
 [[1 2]
 [3 4]]

combined row:
 [[1 2]
 [3 4]
 [5 6]]
combined column:
 [[1 2 7]
 [3 4 8]]


# delete elements

In [17]:
arr3=np.array([1 , 2, 3, 4, 5])
deleted=np.delete(arr3, 2)
print("array after deletion:\n" , deleted)

array after deletion:
 [1 2 4 5]
