# LEARN ABOUT NUMPY

In [1]:
import numpy as np

# creating array from list

In [2]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_4d = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],
                   [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]])
arr_5d = np.array([[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],
                    [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]],
                   [[[[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]],
                    [[[37, 38, 39], [40, 41, 42]], [[43, 44, 45], [46, 47, 48]]]]])
arr_6d = np.array([[[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],
                     [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]],
                    [[[[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]],
                     [[[37, 38, 39], [40, 41, 42]], [[43, 44, 45], [46, 47, 48]]]]],
                   [[[[[49, 50, 51], [52, 53, 54]], [[55, 56, 57], [58, 59, 60]]],
                     [[[61, 62, 63], [64, 65, 66]], [[67, 68, 69], [70, 71, 72]]]],
                    [[[[73, 74, 75], [76, 77, 78]], [[79, 80, 81], [82, 83, 84]]],
                     [[[85, 86, 87], [88, 89, 90]], [[91, 92, 93], [94, 95, 96]]]]]])
arr_7d = np.array([[[[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],
                      [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]],
                     [[[[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]],
                      [[[37, 38, 39], [40, 41, 42]], [[43, 44, 45], [46, 47, 48]]]]],
                    [[[[[49, 50, 51], [52, 53, 54]], [[55, 56, 57], [58, 59, 60]]],
                      [[[61, 62, 63], [64, 65, 66]], [[67, 68, 69], [70, 71, 72]]]],
                     [[[[73, 74, 75], [76, 77, 78]], [[79, 80, 81], [82, 83, 84]]],
                      [[[85, 86, 87], [88, 89, 90]], [[91, 92, 93], [94, 95, 96]]]]],
                   [[[[[97, 98, 99], [100, 101, 102]], [[103, 104, 105], [106, 107, 108]]],
                      [[[109, 110, 111], [112, 113, 114]], [[115, 116, 117], [118, 119, 120]]]],
                    [[[[121, 122, 123], [124, 125, 126]], [[127, 128, 129], [130, 131, 132]]],
                      [[[133, 134, 135], [136, 137, 138]], [[139, 140, 141], [142, 143, 144]]]]],
                   [[[[[145, 146, 147], [148, 149, 150]], [[151, 152, 153], [154, 155, 156]]],
                      [[[157, 158, 159], [160, 161, 162]], [[163, 164, 165], [166, 167, 168]]]],
                    [[[[169, 170, 171], [172, 173, 174]], [[175, 176, 177], [178, 179, 180]]],
                      [[[181, 182, 183], [184, 185, 186]], [[187, 188, 189], [190, 191, 192]]]]]]])
arr_8d = np.array([[[[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],
                      [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]],
                     [[[[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]],
                      [[[37, 38, 39], [40, 41, 42]], [[43, 44, 45], [46, 47, 48]]]]],
                    [[[[[49, 50, 51], [52, 53, 54]], [[55, 56, 57], [58, 59, 60]]],
                      [[[61, 62, 63], [64, 65, 66]], [[67, 68, 69], [70, 71, 72]]]],
                     [[[[73, 74, 75], [76, 77, 78]], [[79, 80, 81], [82, 83, 84]]],
                      [[[85, 86, 87], [88, 89, 90]], [[91, 92, 93], [94, 95, 96]]]]],
                   [[[[[97, 98, 99], [100, 101, 102]], [[103, 104, 105], [106, 107, 108]]],
                      [[[109, 110, 111], [112, 113, 114]], [[115, 116, 117], [118, 119, 120]]]],
                    [[[[121, 122, 123], [124, 125, 126]], [[127, 128, 129], [130, 131, 132]]],
                      [[[133, 134, 135], [136, 137, 138]], [[139, 140, 141], [142, 143, 144]]]]],
                   [[[[[145, 146, 147], [148, 149, 150]], [[151, 152, 153], [154, 155, 156]]],
                      [[[157, 158, 159], [160, 161, 162]], [[163, 164, 165], [166, 167, 168]]]],
                    [[[[169, 170, 171], [172, 173, 174]], [[175, 176, 177], [178, 179, 180]]],
                      [[[181, 182, 183], [184, 185, 186]], [[187, 188, 189], [190, 191, 192]]]]],
                   [[[[[193, 194, 195], [196, 197, 198]], [[199, 200, 201], [202, 203, 204]]],
                      [[[205, 206, 207], [208, 209, 210]], [[211, 212, 213], [214, 215, 216]]]],
                    [[[[217, 218, 219], [220, 221, 222]], [[223, 224, 225], [226, 227, 228]]],
                      [[[229, 230, 231], [232, 233, 234]], [[235, 236, 237], [238, 239, 240]]]]],
                   [[[[[241, 242, 243], [244, 245, 246]], [[247, 248, 249], [250, 251, 252]]],
                      [[[253, 254, 255], [256, 257, 258]], [[259, 260, 261], [262, 263, 264]]]],
                    [[[[265, 266, 267], [268, 269, 270]], [[271, 272, 273], [274, 275, 276]]],
                      [[[277, 278, 279], [280, 281, 282]], [[283, 284, 285], [286, 287, 288]]]]]]])
print("arr_1d:" , arr_1d)
print("arr_2d:" , arr_2d)
print("arr_3d:" , arr_3d)

print("arr_4d:" , arr_4d)
print("arr_5d:" , arr_5d)
print("arr_6d:" , arr_6d)
print("arr_7d:" , arr_7d)


arr_1d: [1 2 3]
arr_2d: [[1 2 3]
 [4 5 6]]
arr_3d: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr_4d: [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
arr_5d: [[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[13 14 15]
    [16 17 18]]

   [[19 20 21]
    [22 23 24]]]]



 [[[[25 26 27]
    [28 29 30]]

   [[31 32 33]
    [34 35 36]]]


  [[[37 38 39]
    [40 41 42]]

   [[43 44 45]
    [46 47 48]]]]]
arr_6d: [[[[[[ 1  2  3]
     [ 4  5  6]]

    [[ 7  8  9]
     [10 11 12]]]


   [[[13 14 15]
     [16 17 18]]

    [[19 20 21]
     [22 23 24]]]]



  [[[[25 26 27]
     [28 29 30]]

    [[31 32 33]
     [34 35 36]]]


   [[[37 38 39]
     [40 41 42]]

    [[43 44 45]
     [46 47 48]]]]]




 [[[[[49 50 51]
     [52 53 54]]

    [[55 56 57]
     [58 59 60]]]


   [[[61 62 63]
     [64 65 66]]

    [[67 68 69]
     [70 71 72]]]]



  [[[[73 74 75]
     [76 77 78]]

    [[79 80 81]
  

# list vs numpy array

In [3]:
py_list=[1 , 2,3 ]
print("py_list:" , py_list*2)
np_array=np.array(py_list) #element-wise operation
print("np_array:" , np_array*2)

py_list: [1, 2, 3, 1, 2, 3]
np_array: [2 4 6]


# time in numpy array vs python list

In [4]:
import time
start = time.time()
list1 = [i*2 for i in range(1000000)]
print("time taken to create list1:", time.time()-start)
start = time.time()
arr1 = np.arange(1000000)*2
print("time taken to create numpy array:", time.time()-start)

time taken to create list1: 0.050318002700805664
time taken to create numpy array: 0.005576610565185547


# creation of array from scratch

In [5]:
zeros=np.zeros((3, 4))
print("zeros:\n" , zeros)
ones=np.ones((3, 4))
print("ones:\n" , ones)

full=np.full((3, 4), 5)
print("full:\n" , full)

random=np.random.random((3, 4))
print("random:\n" , random)

sequence=np.arange(0 , 20 , 2)
print("sequence:\n" , sequence)

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random:
 [[0.48504921 0.02180298 0.01467514 0.65505311]
 [0.07828605 0.32551646 0.27898315 0.25509203]
 [0.77162827 0.79216978 0.08902072 0.09519152]]
sequence:
 [ 0  2  4  6  8 10 12 14 16 18]


# vector , matrix and tensor

In [6]:
vector=np.array([1, 2, 3])
print("vector:\n" , vector)

matrix=np.array([[1, 2, 3], [4, 5, 6]])
print("matrix:\n" , matrix)

tensor=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("tensor:\n" , tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# array properties

In [7]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print("shape of arr:", arr.shape)
print("size of arr:", arr.size)
print("dimension of arr:", arr.ndim)
print("dtype of arr:", arr.dtype)

shape of arr: (2, 3)
size of arr: 6
dimension of arr: 2
dtype of arr: int64


# array reshape

In [8]:
arr=np.arange(10)
print("arr:\n" , arr)
arr1=arr.reshape(2, 5)
print("reshaped arr:\n" , arr1)

flat=arr1.flatten()
print("flattened arr:\n" , flat)


print("reshaped arr:\n" , arr1)

raveled=arr1.ravel()
print("raveled arr:\n" , raveled)

print("reshaped arr:\n" , arr1)

transposed=arr1.T
print("transposed arr:\n" , transposed)

flat1=flat.reshape(1 , 10)
# print("reshaped flat:\n" , flat.reshape(1 , 10))
trans1=flat1.T
print("transposed flat:\n" , trans1)

arr:
 [0 1 2 3 4 5 6 7 8 9]
reshaped arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
flattened arr:
 [0 1 2 3 4 5 6 7 8 9]
reshaped arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
raveled arr:
 [0 1 2 3 4 5 6 7 8 9]
reshaped arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
transposed arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
transposed flat:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
